##Genius Exploration

In [113]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def str_cleaner(s):
    k = s.replace('.','')
    k = k[:2] + '.' + k[2:]
    return float(k)

In [146]:
df = pd.read_csv('data_75m.csv',  sep=', ', delimiter= ';')
df['Latitude'] = df['Latitude'].apply(str_cleaner)
df['Longitude'] = df['Longitude'].apply(str_cleaner)
df['Antena_Latitude'] = 55.472693
df['Antena_Longitude'] = 10.329273 
df['Antena_height'] = 22.5

In [147]:
df

,Date,Time,UTC,Latitude,Longitude,Altitude,Speed,Heading,#Sat,NR-ARFCN,...,SSS_PBCH-RSRQ,SSS_PBCH-RePower,SS_PBCH-SINR,SS_PBCH-RSRP,SS_PBCH-RSRQ,SS_PBCH-RePower,DeviceID,Antena_Latitude,Antena_Longitude,Antena_height
0,"0,611597222",12:35:05.151,1660469703,55.469870,10.329676,22.32,00.04,139.76,7,630048,...,-12.3,-93.9,03.03,-95.8,-12.3,-94.1,1,55.472693,10.329273,22.5
1,"0,611597222",12:35:09.709,1660469709,55.469873,10.329676,"0,88125",00.00,139.76,7,630048,...,-12.3,-94.2,03.05,-96.0,-12.3,-94.4,1,55.472693,10.329273,22.5
2,"0,611597222",12:35:09.709,1660469709,55.469873,10.329676,"0,88125",00.00,139.76,7,630048,...,-22.9,-94.2,-11.7,-106.4,-22.7,-94.4,1,55.472693,10.329273,22.5
3,"0,611597222",12:35:10.850,1660469709,55.469873,10.329676,"0,88125",00.00,139.76,7,630048,...,-11.1,-91.7,10.02,-92.2,-11.1,-91.8,1,55.472693,10.329273,22.5
4,"0,611597222",12:35:10.870,1660469709,55.469873,10.329676,"0,88125",00.00,139.76,7,630048,...,NaN,NaN,09.01,-92.3,-11.1,-91.8,1,55.472693,10.329273,22.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11523,"0,611597222",12:41:47.954,1660470107,55.469859,10.329695,"0,63125",00.04,257.95,8,630048,...,-19.1,-98.3,-7.6,-106.6,-19.1,-98.3,1,55.472693,10.329273,22.5
11524,"0,611597222",12:41:47.994,1660470107,55.469859,10.329695,"0,63125",00.04,257.95,8,630048,...,-19.1,-98.3,-7.8,-106.6,-19.1,-98.3,1,55.472693,10.329273,22.5
11525,"0,611597222",12:41:48.374,1660470107,55.469859,10.329695,"0,63125",00.04,257.95,8,630048,...,-19.1,-98.3,-7.2,-105.5,-19.1,-98.3,1,55.472693,10.329273,22.5
11526,"0,611597222",12:41:48.414,1660470107,55.469859,10.329695,"0,63125",00.04,257.95,8,630048,...,-19.1,-98.3,-9.1,-107.6,-19.1,-98.3,1,55.472693,10.329273,22.5
11527,"0,611597222",12:41:48.434,1660470107,55.469859,10.329695,"0,63125",00.04,257.95,8,630048,...,-19.1,-98.3,-9.2,-107.6,-19.1,-98.3,1,55.472693,10.329273,22.5

In [148]:
df.columns

Index(['Date', 'Time', 'UTC', 'Latitude', 'Longitude', 'Altitude', 'Speed',
       'Heading', '#Sat', 'NR-ARFCN', 'SSRef', 'Band', 'PCI', 'SSB Idx',
       'SSB Idx Mod8', 'SSB-RSSI', 'SSS-SINR', 'SSS-RSRP', 'SSS-RSRQ',
       'SSS-RePower', 'MCC', 'MNC', 'LAC', 'RNC-CellID(H)', 'RNC-CellID(D)',
       'ToA(PPS)', 'ToA(CIR)', 'MIB_Sfn', 'MIB_ScsCommon30or120kHz',
       'MIB_SsbSubcarrierOffset', 'MIB_DmrsTypeAPositionPos3',
       'MIB_PdcchConfigSib1', 'MIB_CellNotBarred',
       'MIB_IntraFreqReselectionNotAllowed', 'DM_RS-SINR', 'DM_RS-RSRP',
       'DM_RS-RSRQ', 'DM_RS-RePower', 'PBCH-SINR', 'PBCH-RSRP', 'PBCH-RSRQ',
       'PBCH-RePower', 'PSS-SINR', 'PSS-RSRP', 'PSS-RSRQ', 'PSS-RePower',
       'SSS_PBCH-SINR', 'SSS_PBCH-RSRP', 'SSS_PBCH-RSRQ', 'SSS_PBCH-RePower',
       'SS_PBCH-SINR', 'SS_PBCH-RSRP', 'SS_PBCH-RSRQ', 'SS_PBCH-RePower',
       'DeviceID', 'Antena_Latitude', 'Antena_Longitude', 'Antena_height'],
      dtype='object')

In [154]:
cols = [ 'Latitude', 'Longitude', 'Altitude', 'SSS-RSRP', 'Antena_Latitude', 'Antena_Longitude',  'Antena_height', 'MAX_RSRP' ]

In [155]:
custom_df = df[cols]
custom_df['Altitude'] = 75

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [156]:
train_df = custom_df.iloc[:10000]
train_df

,Latitude,Longitude,Altitude,SSS-RSRP,Antena_Latitude,Antena_Longitude,Antena_height
0,55.469870,10.329676,75,-97.2,55.472693,10.329273,22.5
1,55.469873,10.329676,75,-96.7,55.472693,10.329273,22.5
2,55.469873,10.329676,75,-105.1,55.472693,10.329273,22.5
3,55.469873,10.329676,75,-92.5,55.472693,10.329273,22.5
4,55.469873,10.329676,75,-92.9,55.472693,10.329273,22.5
...,...,...,...,...,...,...,...
9995,55.469858,10.329697,75,-120.8,55.472693,10.329273,22.5
9996,55.469858,10.329697,75,-93.8,55.472693,10.329273,22.5
9997,55.469858,10.329697,75,-94.3,55.472693,10.329273,22.5
9998,55.469858,10.329697,75,-92.5,55.472693,10.329273,22.5
9999,55.469858,10.329697,75,-92.9,55.472693,10.329273,22.5

In [157]:
train_df = custom_df.iloc[:10000]
test_df = custom_df.iloc[10000:]
train_ip = train_df[['Latitude', 'Longitude', 'Altitude', 'Antena_Latitude', 'Antena_Longitude', 'Antena_height' ]]
train_op = train_df['SSS-RSRP']

test_ip = test_df[['Latitude', 'Longitude', 'Altitude', 'Antena_Latitude', 'Antena_Longitude', 'Antena_height'  ]]
test_op = test_df['SSS-RSRP']

In [158]:
train_op

0       -97.2
1       -96.7
2      -105.1
3       -92.5
4       -92.9
        ...
9995   -120.8
9996    -93.8
9997    -94.3
9998    -92.5
9999    -92.9
Name: SSS-RSRP, Length: 10000, dtype: float64

In [159]:
reg = LinearRegression().fit(train_ip, train_op)

In [160]:
pred_test_op = reg.predict(test_ip)

In [163]:
## Error Ca;culation
error = mean_squared_error(test_op, pred_test_op)
error

223.02923569282018

In [162]:
type(df['Altitude'][1])

str

In [145]:
df['Altitude'].apply(float)

ValueError: could not convert string to float: '0,88125'